version: "3"

services:
  drupal:
    image: bitnami/drupal:latest


  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=<Your Student Number>
      - MYSQL_DATABASE=final
    

  nginx:
    image: nginx
    

  certbot:
    image: certbot
    

